{44057: 0}
{44057: 0.5351548618637025}
{44057: 0.554951885715127}
{44057: 0.5615909537300467}
{44057: 1.0972644560970366}
{44057: 1.7676118854433298}
{44057: 2.4100783332251012}
{44057: 2.812188921030611}
{44057: 3.4838053290732205}
{44057: 3.8239245070144534}
{44057: 4.480338437948376}
{44057: 4.792269445955753}
{44057: 5.332699663005769}
{44057: 5.608928047120571}
{44057: 6.186631076969206}
{44057: 6801.199156506918}
{44057: 6801.6276726080105}
{44057: 12710.580907368101}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
