{41281: 0}
{41281: 0.006615519057959318}
{41281: 0.013159121852368116}
{41281: 0.02983402693644166}
{41281: 0.039375459775328636}
{41281: 0.04896038398146629}
{41281: 0.05839386023581028}
{41281: 0.08087977347895503}
{41281: 0.09056768426671624}
{41281: 0.12194050895050168}
{41281: 0.1316430871374905}
{41281: 0.17093041352927685}
{41281: 0.18064870685338974}
{41281: 0.22054324159398675}
{41281: 0.23763418337330222}
{41281: 0.28323533153161407}
{41281: 0.296608196105808}
{41281: 0.333981113974005}
{41281: 0.3590833698399365}
{41281: 0.7226423597894609}
{41281: 1.4067434957250953}
{41281: 1.8076054938137531}
{41281: 2.4008301054127514}
{41281: 2.772041260264814}
{41281: 3.223705977667123}
{41281: 3.624756891746074}
{41281: 3.7565145706757903}
{41281: 4.123168489895761}
{41281: 4.130076473113149}
{41281: 4.987264771014452}
{41281: 5.723207745235413}
{41281: 8763.386993335094}
{41281: 8764.889863815159}
{41281: 14876.514399883337}
{41281: 19909.767925544176}
{41281: 19910.002178467344}
{41281: 19910.076329410076}
{41281: 19910.248668049928}
{41281: 19910.252449318767}
{41281: 19910.426668502856}
{41281: 19910.430441692006}
{41281: 19910.601872222964}
{41281: 19910.605635018088}
{41281: 19911.059912343044}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
