{15162: 0}
{15162: 0.006290477234870195}
{15162: 0.012375705409795046}
{15162: 0.022160019725561142}
{15162: 0.03149713296443224}
{15162: 0.05282264295965433}
{15162: 0.062065165024250746}
{15162: 0.09340420411899686}
{15162: 0.1026656273752451}
{15162: 0.1712044053710997}
{15162: 0.18042925233021379}
{15162: 0.21971459174528718}
{15162: 0.23582545574754477}
{15162: 0.28162666875869036}
{15162: 0.30277402279898524}
{15162: 0.3453400516882539}
{15162: 0.3680643714033067}
{15162: 0.401805164758116}
{15162: 0.4250602489337325}
{15162: 0.7725955238565803}
{15162: 1.1537353130988777}
{15162: 1.5056604179553688}
{15162: 1.627553251106292}
{15162: 1.9719847030937672}
{15162: 1.9783744420856237}
{15162: 4892.728936324827}
{15162: 18200.794452891685}
{15162: 18201.240244925488}
{15162: 18201.35599663481}
{15162: 18201.64988674177}
{15162: 18201.656159556005}
{15162: 25356.464519990142}
{15162: 25356.974323191214}
{15162: 25357.63654542854}
{15162: 27401.494211726356}
{15162: 30218.95650014747}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
