{36837: 0}
{36837: 0.5610617240890861}
{36837: 0.5817300034686923}
{36837: 0.588686391711235}
{36837: 1.1523785647004843}
{36837: 1.8643363192677498}
{36837: 2.5256903911940753}
{36837: 3.3364349571056664}
{36837: 4.027592295315117}
{36837: 4.37315084412694}
{36837: 4.9964059689082205}
{36837: 5.345478370785713}
{36837: 5.860202047973871}
{36837: 6.1883571478538215}
{36837: 6.74508141214028}
{36837: 7.067404126282781}
{36837: 7.638254580553621}
{36837: 7.991569442208856}
{36837: 8.50438042357564}
{36837: 8.855906549841166}
{36837: 8.862595753744245}
{36837: 11243.309279896785}
{36837: 11243.800108192023}
{36837: 11244.217051780317}
{36837: 11244.63807084551}
{36837: 11245.168996067718}
{36837: 11246.4717155369}
{36837: 11246.7725471952}
{36837: 11246.776341216173}
{36837: 11246.780334779993}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'CODEDATACOPY'
